import { type AppType } from "next/app";
import { api } from "~/utils/api";
import "~/styles/globals.css";
import Head from "next/head";
import { Toaster } from "~/components/ui/toaster";
import Header from "~/components/ui/header";
import { ThemeProvider } from "~/components/theme/theme-provider";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Fast Sell</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <Header />
        <main className="flex grow flex-col items-center justify-start bg-background">
          <Component {...pageProps} />
        </main>
        <Toaster />
      </ThemeProvider>
    </>
  );
};

export default api.withTRPC(MyApp);
