import Head from "next/head";
import { Button } from "~/components/ui/button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            STOREEEEE
          </h1>
        </div>
        <Button size="lg">BUY NOW</Button>
        <Button variant="secondary" size="lg">
          SELL NOW
        </Button>
        <Button variant="destructive" size="lg">
          DESTROY NOW
        </Button>
      </main>
    </>
  );
}
